"""arreglando Torneo

Revision ID: 285130386639
Revises: 58f716014722
Create Date: 2025-07-10 17:19:50.518868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285130386639'
down_revision: Union[str, None] = '58f716014722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('torneos', 'mesas',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('torneos', 'mesas',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
