"""modificando Partido y mesa denuevo

Revision ID: 30d03742d4e9
Revises: 94204d0f8fa1
Create Date: 2025-07-10 21:00:07.551930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d03742d4e9'
down_revision: Union[str, None] = '94204d0f8fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mesas__partidos', table_name='mesas')
    op.drop_constraint('mesas_partido_id_fkey', 'mesas', type_='foreignkey')
    op.drop_column('mesas', 'partido_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesas', sa.Column('partido_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mesas_partido_id_fkey', 'mesas', 'partidos', ['partido_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_mesas__partidos', 'mesas', ['partido_id'], unique=False)
    # ### end Alembic commands ###
