"""arreglando Torneo

Revision ID: 58f716014722
Revises: b74e081fc614
Create Date: 2025-07-10 17:10:41.241490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f716014722'
down_revision: Union[str, None] = 'b74e081fc614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torneos', sa.Column('mesas_disponibles', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('torneos', 'mesas_disponibles')
    # ### end Alembic commands ###
