"""modificando Categoria

Revision ID: 70d0076305db
Revises: 30d03742d4e9
Create Date: 2025-07-10 21:08:01.388184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d0076305db'
down_revision: Union[str, None] = '30d03742d4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('nombre', sa.Text(), nullable=False))
    op.add_column('categorias', sa.Column('sets_por_partido', sa.Integer(), nullable=False))
    op.add_column('categorias', sa.Column('puntos_por_sets', sa.Integer(), nullable=False))
    op.drop_column('categorias', 'sets_x_partido')
    op.drop_column('categorias', 'puntos_x_set')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('puntos_x_set', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('categorias', sa.Column('sets_x_partido', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('categorias', 'puntos_por_sets')
    op.drop_column('categorias', 'sets_por_partido')
    op.drop_column('categorias', 'nombre')
    # ### end Alembic commands ###
