"""modificando Mesa

Revision ID: 792489141151
Revises: d2712abc9bac
Create Date: 2025-07-10 19:50:22.206714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792489141151'
down_revision: Union[str, None] = 'd2712abc9bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mesas', 'partidos',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mesas', 'partidos',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
