"""fix_inscripciones_id_autoincrement2

Revision ID: 8bbd94e4f976
Revises: 
Create Date: 2025-07-10 23:00:54.716349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbd94e4f976'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asociaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('ciudad', sa.Text(), nullable=False),
    sa.Column('pais', sa.Text(), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('edad_min', sa.Integer(), nullable=False),
    sa.Column('edad_max', sa.Integer(), nullable=False),
    sa.Column('genero', sa.Text(), nullable=False),
    sa.Column('sets_por_partido', sa.Integer(), nullable=False),
    sa.Column('puntos_por_sets', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('torneos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('fechas_inscripcion', sa.Date(), nullable=False),
    sa.Column('fecha_competencia', sa.Date(), nullable=False),
    sa.Column('mesas_requeridas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_torneos',
    sa.Column('categorias', sa.Integer(), nullable=False),
    sa.Column('torneos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorias'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['torneos'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('categorias', 'torneos')
    )
    op.create_index('idx_categorias_torneos', 'categorias_torneos', ['torneos'], unique=False)
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_equipo', sa.Text(), nullable=False),
    sa.Column('categorias', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorias'], ['categorias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_equipo__categorias', 'equipo', ['categorias'], unique=False)
    op.create_table('jugador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.Text(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.Text(), nullable=False),
    sa.Column('ciudad', sa.Text(), nullable=False),
    sa.Column('asociaciones', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('telefono', sa.Text(), nullable=False),
    sa.Column('fecha_inscripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asociaciones'], ['asociaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jugador__asociaciones', 'jugador', ['asociaciones'], unique=False)
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('torneo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mesa__torneo', 'mesas', ['torneo_id'], unique=False)
    op.create_table('equipo_jugador',
    sa.Column('equipo', sa.Integer(), nullable=False),
    sa.Column('jugador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo'], ['equipo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jugador'], ['jugador.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equipo', 'jugador')
    )
    op.create_index('idx_equipo_jugador', 'equipo_jugador', ['jugador'], unique=False)
    op.create_table('equipo_jugador_2',
    sa.Column('equipo', sa.Integer(), nullable=False),
    sa.Column('jugador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo'], ['equipo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jugador'], ['jugador.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equipo', 'jugador')
    )
    op.create_index('idx_equipo_jugador_2', 'equipo_jugador_2', ['jugador'], unique=False)
    op.create_table('inscripciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categorias', sa.Integer(), nullable=False),
    sa.Column('torneos', sa.Integer(), nullable=False),
    sa.Column('jugador', sa.Integer(), nullable=False),
    sa.Column('equipo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorias'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipo'], ['equipo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jugador'], ['jugador.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['torneos'], ['torneos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inscripciones__categorias', 'inscripciones', ['categorias'], unique=False)
    op.create_index('idx_inscripciones__equipo', 'inscripciones', ['equipo'], unique=False)
    op.create_index('idx_inscripciones__jugador', 'inscripciones', ['jugador'], unique=False)
    op.create_index('idx_inscripciones__torneos', 'inscripciones', ['torneos'], unique=False)
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.DateTime(), nullable=False),
    sa.Column('es_bye', sa.Boolean(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('categorias', sa.Integer(), nullable=False),
    sa.Column('jugador1', sa.Integer(), nullable=True),
    sa.Column('jugador2', sa.Integer(), nullable=True),
    sa.Column('equipo1', sa.Integer(), nullable=True),
    sa.Column('equipo2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categorias'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipo1'], ['equipo.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo2'], ['equipo.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['jugador1'], ['jugador.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['jugador2'], ['jugador.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mesa_id')
    )
    op.create_index('idx_partidos__categorias', 'partidos', ['categorias'], unique=False)
    op.create_index('idx_partidos__equipo1', 'partidos', ['equipo1'], unique=False)
    op.create_index('idx_partidos__equipo2', 'partidos', ['equipo2'], unique=False)
    op.create_index('idx_partidos__jugador1', 'partidos', ['jugador1'], unique=False)
    op.create_index('idx_partidos__jugador2', 'partidos', ['jugador2'], unique=False)
    op.create_table('fases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('torneos', sa.Integer(), nullable=False),
    sa.Column('partidos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partidos'], ['partidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['torneos'], ['torneos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fases__partidos', 'fases', ['partidos'], unique=False)
    op.create_index('idx_fases__torneos', 'fases', ['torneos'], unique=False)
    op.create_table('resultados_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_set', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('partidos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partidos'], ['partidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resultados_set__partidos', 'resultados_set', ['partidos'], unique=False)
    op.create_table('categorias_fases',
    sa.Column('categorias', sa.Integer(), nullable=False),
    sa.Column('fases', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorias'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['fases'], ['fases.id'], ),
    sa.PrimaryKeyConstraint('categorias', 'fases')
    )
    op.create_index('idx_categorias_fases', 'categorias_fases', ['fases'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_categorias_fases', table_name='categorias_fases')
    op.drop_table('categorias_fases')
    op.drop_index('idx_resultados_set__partidos', table_name='resultados_set')
    op.drop_table('resultados_set')
    op.drop_index('idx_fases__torneos', table_name='fases')
    op.drop_index('idx_fases__partidos', table_name='fases')
    op.drop_table('fases')
    op.drop_index('idx_partidos__jugador2', table_name='partidos')
    op.drop_index('idx_partidos__jugador1', table_name='partidos')
    op.drop_index('idx_partidos__equipo2', table_name='partidos')
    op.drop_index('idx_partidos__equipo1', table_name='partidos')
    op.drop_index('idx_partidos__categorias', table_name='partidos')
    op.drop_table('partidos')
    op.drop_index('idx_inscripciones__torneos', table_name='inscripciones')
    op.drop_index('idx_inscripciones__jugador', table_name='inscripciones')
    op.drop_index('idx_inscripciones__equipo', table_name='inscripciones')
    op.drop_index('idx_inscripciones__categorias', table_name='inscripciones')
    op.drop_table('inscripciones')
    op.drop_index('idx_equipo_jugador_2', table_name='equipo_jugador_2')
    op.drop_table('equipo_jugador_2')
    op.drop_index('idx_equipo_jugador', table_name='equipo_jugador')
    op.drop_table('equipo_jugador')
    op.drop_index('idx_mesa__torneo', table_name='mesas')
    op.drop_table('mesas')
    op.drop_index('idx_jugador__asociaciones', table_name='jugador')
    op.drop_table('jugador')
    op.drop_index('idx_equipo__categorias', table_name='equipo')
    op.drop_table('equipo')
    op.drop_index('idx_categorias_torneos', table_name='categorias_torneos')
    op.drop_table('categorias_torneos')
    op.drop_table('torneos')
    op.drop_table('categorias')
    op.drop_table('asociaciones')
    # ### end Alembic commands ###
