"""modificando Mesa y Torneo

Revision ID: 9044c34d34df
Revises: 285130386639
Create Date: 2025-07-10 19:31:20.616494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9044c34d34df'
down_revision: Union[str, None] = '285130386639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesas', sa.Column('torneo_id', sa.Integer(), nullable=True))
    op.create_index('idx_mesa__torneo', 'mesas', ['torneo_id'], unique=False)
    op.create_foreign_key(None, 'mesas', 'torneos', ['torneo_id'], ['id'], ondelete='CASCADE')
    op.add_column('torneos', sa.Column('mesas_requeridas', sa.Integer(), nullable=False))
    op.drop_index('idx_torneos__mesas', table_name='torneos')
    op.drop_constraint('torneos_mesas_fkey', 'torneos', type_='foreignkey')
    op.drop_column('torneos', 'mesas_disponibles')
    op.drop_column('torneos', 'mesas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torneos', sa.Column('mesas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('torneos', sa.Column('mesas_disponibles', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('torneos_mesas_fkey', 'torneos', 'mesas', ['mesas'], ['id'], ondelete='CASCADE')
    op.create_index('idx_torneos__mesas', 'torneos', ['mesas'], unique=False)
    op.drop_column('torneos', 'mesas_requeridas')
    op.drop_constraint(None, 'mesas', type_='foreignkey')
    op.drop_index('idx_mesa__torneo', table_name='mesas')
    op.drop_column('mesas', 'torneo_id')
    # ### end Alembic commands ###
