"""modificando Partido

Revision ID: 94204d0f8fa1
Revises: ece230edd063
Create Date: 2025-07-10 20:54:22.190098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94204d0f8fa1'
down_revision: Union[str, None] = 'ece230edd063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesas', sa.Column('partido_id', sa.Integer(), nullable=True))
    op.drop_index('idx_mesas__partidos', table_name='mesas')
    op.create_index('idx_mesas__partidos', 'mesas', ['partido_id'], unique=False)
    op.drop_constraint('mesas_partidos_fkey', 'mesas', type_='foreignkey')
    op.create_foreign_key(None, 'mesas', 'partidos', ['partido_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mesas', 'partidos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesas', sa.Column('partidos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mesas', type_='foreignkey')
    op.create_foreign_key('mesas_partidos_fkey', 'mesas', 'partidos', ['partidos'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_mesas__partidos', table_name='mesas')
    op.create_index('idx_mesas__partidos', 'mesas', ['partidos'], unique=False)
    op.drop_column('mesas', 'partido_id')
    # ### end Alembic commands ###
