"""Modificando Asociaciones

Revision ID: b74e081fc614
Revises: b1df4f1e9e54
Create Date: 2025-07-09 20:45:42.687603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74e081fc614'
down_revision: Union[str, None] = 'b1df4f1e9e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asociaciones', sa.Column('nombre', sa.Text(), nullable=False))
    op.add_column('asociaciones', sa.Column('fecha_inscripcion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asociaciones', 'fecha_inscripcion')
    op.drop_column('asociaciones', 'nombre')
    # ### end Alembic commands ###
