"""modificando Mesa y Torneo

Revision ID: d2712abc9bac
Revises: 9044c34d34df
Create Date: 2025-07-10 19:37:53.739972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2712abc9bac'
down_revision: Union[str, None] = '9044c34d34df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesas', sa.Column('numero', sa.Integer(), nullable=False))
    op.add_column('mesas', sa.Column('fecha_creacion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mesas', 'fecha_creacion')
    op.drop_column('mesas', 'numero')
    # ### end Alembic commands ###
