"""modificando Partido y mesa

Revision ID: ece230edd063
Revises: 792489141151
Create Date: 2025-07-10 20:44:29.346777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece230edd063'
down_revision: Union[str, None] = '792489141151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidos', sa.Column('mesa_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'partidos', ['mesa_id'])
    op.create_foreign_key(None, 'partidos', 'mesas', ['mesa_id'], ['id'], ondelete='SET NULL')
    op.drop_column('partidos', 'mesa_asignada')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidos', sa.Column('mesa_asignada', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'partidos', type_='foreignkey')
    op.drop_constraint(None, 'partidos', type_='unique')
    op.drop_column('partidos', 'mesa_id')
    # ### end Alembic commands ###
